MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # tag: yang adds
  DEVICE: 'cuda:0'
  # tag: yang adds
  SOFT_VAL: -1.0
  LAYER_LEVELS: [0, 1]

  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # tag: yang adds
    RPN_HEAD: "SingleConvRPNMaskHead"

  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.01
    DA_INS_GRL_WEIGHT: 0.1
    COS_WEIGHT: 0.1
DATASETS:
  SOURCE_TRAIN: ("synthetic_data_wdt",)
  TARGET_TRAIN: ("xilin_wdt_train",)
  TEST: ("xilin_wdt_test",)
  #tag: yang adds
  DATA_SEED: 1
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1600
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000,)
  MAX_ITER: 70000
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
